services:
  web:
    build: .
    container_name: biscayne-hoa
    restart: always
    ports:
      - "8080:3000"
    #environment:
    #  - PORT=3000
    #command: ["npm", "run", "dev", "--", "-p", "3000"]
